### ISSUE TITLE
Sorry for intruding on your layout again...

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/corona#10]
Hi there,

To better manage what I've reported on Issue #8 I suggest the following:

* Put `cgCases`, `rgDataType`, `btnUpdate` and `btnClear` inside a `TPanel` with `Align=alTop`
* Make `TreeView.Align=alClient` and you can do away with all the Anchors you set up.

This way, no overlapping on the buttons and it's all contained.

**Again, really sorry if it's too much intruding.**

Cheers,
Gus

**Comment by wp-xyz** [comment]
I think the problem is in the CheckGroup and RadioGroup which must be autosized because font size depends on widgetset and thus it is possible that text may be truncated. This leads to a chain of actions: Once the width of these controls is known the width of the LeftPanel must be adjusted (by AutoSize=true, too). The Constraints.MinWidth of the LeftPanel must be set to this "optimal" width, so that the panel cannot shrink any more. And finally the AutoSize of the LeftPanel must be released to make the splitter work.
The problem in the current code is that this happens in the OnCreate event where autosizing has not yet been executed. It should be delayed to OnActivate or OnShow. But then I see a short flicker of the form during the resize action.
Therefore, I am introducing now a method "BeforeRun" which is called in the lpr file before Application.Run occurs. At this point, all the initialization has been done, and the form is not yet visible. So this should be the correct place to make final size adjustments.

**Comment by gcarreno** [comment]
Hey There,

What you say makes sense and looking at the code it also makes sense it would work.

Somehow, after `git pull`ing, deleting corona.cfg and recompiling and running the application, absolutely nothing changed. Which baffles me **completely**

Maybe `TPairSplitter` would solve some of this? I dunno!!

Ah, you could also do with saving `TMainForm.WindowState` in the config please.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey there,

I'll try and cross compile into Win64 on my Ubuntu machine and then through `wine` see if the `BeforeRun()` procedure has any effect on it.

Cheers,
Gus

**Comment by wp-xyz** [comment]
I cloned the git on a VM with Linux Mint, no problems with autosizing.
I will not switch to PairSplitter, it has some issues (but I forgot what...)
WindowState is persistent now.

**Comment by gcarreno** [comment]
Thanks!!!
